### ISSUE TITLE
Feature 1: User can see the match fixtures for todays games

### ISSUE THREAD

**Issue by jdfenlason** [jdfenlason/FotBets#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see the match fixtures for todays games

## 📐 Functionality

User will be able to see the match fixtures for today's matches 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-05-24 at 1 56 58 PM](https://user-images.githubusercontent.com/78828085/119388343-29f67280-bc98-11eb-8571-49169137742a.png)
![Screen Shot 2021-05-24 at 1 58 03 PM](https://user-images.githubusercontent.com/78828085/119388344-29f67280-bc98-11eb-97bd-ef8b32e94dcf.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to  include a users table
- [x] Update `data.sql` to have  usersname, userId, createdAt, tokens amount

### ☁️ Server
- [x] Update `server/index.js` add a HTTP GET Request 
- [x] Test with HTTPie 
- [x] Handle all errors and respond to the client

### ⚡ Client
- [x] Create header component
- [x] In the header put the title of the app 'FotBets' 
- [x] Create a component to handle the display of match fixtures for today's games
- [x] Create cards that API-Football will render data to using dummy data first
- [x] Create heading below header that says today's fixtures 
- [x] Create a header above the cards that shows which league the cards are coming from
- [x] include the league logo 
- [x] Fetch the data from the API-Football and render the relative data points
- [x] Map through the array and create a list of cards for all of the matches 
- [x] If there are no games for today then:  "No upcoming fixtures" should be used

### 🧑‍⚕️ Clean Up
- [x] Make sure that the database is populated with an admin user account 
- [x] Make sure the data being displayed includes: Home, Away Logos and names as well as kickoff and kickoff time
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
