### ISSUE TITLE
Feature 8: User can see previous games results and bets are validated 

### ISSUE THREAD

**Issue by jdfenlason** [jdfenlason/FotBets#19]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to to  include a table that has json cache column for the previous days results
- [x] add date column 
- [x] add league column 
- [x] add json cache column 

### ☁️ Server

- [x] Update `server/index.js` to contain a route that hits api everyday for yesterday's results 
- [x] if there is something in the response save it to the cache and then send to client.
- [x] if there is nothing in the response don't do anything (means no games yesterday) 
- [x] create helper function that decides the winner of the game by returning the team id 
- [x] reference stored Id in wagerInput against Id from helper function if they are not === that means loss 
- [x] Create aggregate in order to deduct tokens when: 1 a bet is made, a bet is lost 
- [x] create aggergate in order to add points when tokens are won via a bet
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client
- [x] Create new state that will hold past results for the last three days.  Filter on client side via date 
- [x] Update sub-component to  get data from the days that have already gone by 
- [x] create a new component to show the scores of the past games in fixturesList 
- [x] Change fixture button click to show on new page and get bet to show as well 
- [x] date-picker needs to reset bet- id back to empty '' 
- [x] conditionally close bet input by time /// timestamp to timestamp from utcDate 
- [x] grab timestamp from wagerDetails and do similar process as checkbet in wager submit
- [x] create new state for betTimestamp to handle new timestamp 
- [x] make sure to reset timestamp with others in fixture container component 
- [ ] 

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
