### ISSUE TITLE
Feature 2: User can see the match details for selected match

### ISSUE THREAD

**Issue by jdfenlason** [jdfenlason/FotBets#2]
## ⚙️ Feature

Users will be able to click on a match fixture card and see additional information about the match they selected

## 📐 Functionality

The user will be able to click on a match card seeing the match details for that day's games

## 🖼️ Wireframes

![Screen Shot 2021-05-24 at 2 25 30 PM](https://user-images.githubusercontent.com/78828085/119391080-ebfb4d80-bc9b-11eb-83b9-4a902acb9a39.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to respond to the client and  query the database and being filtered by fixtureId 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component that opens when the user clicks on the match card and closes when the user clicks on the card again
- [x] Create a new state that has a toggle for the card to appear and hid
- [x] Create a table that shows the relative db information 
- [x] fetch the database 
- [x] confirm that the card is being clicked by the correct fixture id
- [x] add a footer component at the bottom of the page 
- [x] add a home icon that clicks back to the home page
- [x] make sure that all cards are clickable and have the information that relates to their games

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
