### ISSUE TITLE
Feature 3: User can see past/future match fixtures 

### ISSUE THREAD

**Issue by jdfenlason** [jdfenlason/FotBets#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can click on a given day and the fixture results or upcoming fixtures will be presented to them

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-05-24 at 2 27 21 PM](https://user-images.githubusercontent.com/78828085/119391295-2d8bf880-bc9c-11eb-86fe-73d67d2dabe1.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js' bring all games down at a single time a filter on client side
- [x] Delete old route that only requested the current day.

### ⚡ Client

- [x] Create a component to  handle date change events
- [x] create date strip component that has 7 days 
- [x] create 3  date items in the future  
- [x] create 3 date items in the past 
- [x] Update component to handle token change amount 
- [x] separate the  input wager component into it's own component

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
