### ISSUE TITLE
Feature 4: User can click on their profile 

### ISSUE THREAD

**Issue by jdfenlason** [jdfenlason/FotBets#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click on their profile to see their rank and current token totals 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-05-24 at 2 29 22 PM](https://user-images.githubusercontent.com/78828085/119391605-8eb3cc00-bc9c-11eb-9ead-2972f16d79a4.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to add consistency to variable names from front end to back end to database
- [x] Update `data.sql` to have another user

### ☁️ Server

- [x] Test with HTTPie
- [x] add a route to deal with front end get request for profile information
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to display profile
- [x] add the tokens icon and amount in the header
- [x] Update component wager component to display if a fixture has been bet on in the past or not. 
- [x] render profile component when the profile icon at the bottom of the screen is pressed 
- [x] add the trophy icon to the footer in order to bring balance as three is better than three
- [x] add request for the profile information from the data base 

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
