### ISSUE TITLE
Feature 5: User can make a bet on a game 

### ISSUE THREAD

**Issue by jdfenlason** [jdfenlason/FotBets#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can make a bet on a game if they have enough tokens

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-05-24 at 2 31 28 PM](https://user-images.githubusercontent.com/78828085/119391808-d3d7fe00-bc9c-11eb-91ca-c583e4de33a0.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to  hold new table to keep json cache for bets for the week 
- [x] update 'schema.sql' to store user bets 
- [x] Update `data.sql` to ...

### ☁️ Server

- [x] Update `server/index.js` to ...
- [x] -create new route that gets all odds for the upcoming week from third party api
- [x] -create new POST route that sends information from an input to the database 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to render the information for the odds
- [x] create a function component that will render with the odds ratios 
- [x] create a function  component that will handle the input and form control
- [x] if user creates an invalid query than they should be told what the error is
- [x] create enter button that submits form and disappears after the first submit.  All bets are final. 
- [x] make a button around the team logo image so that it is clickable somewhat of a radio button field

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
