### ISSUE TITLE
Feature 6: User can see their current and past bets 

### ISSUE THREAD

**Issue by jdfenlason** [jdfenlason/FotBets#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-05-24 at 2 33 15 PM](https://user-images.githubusercontent.com/78828085/119391918-fff37f00-bc9c-11eb-9b35-f8e9dd2e6f9b.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database
- [x] add new schema that joins bet information

### ☁️ Server

- [x] Test with HTTPie
- [x] Handle all errors and respond to the client
- [x] add new route request last 3 bets from server on client side 
- [x] add new 

### ⚡ Client

- [x] Update component to display the last 5 bets using cards 
- [x] create new request from client side that gets information past bet information when the client is loading
- [x] make sure that newly initiated bets are represented into state so there is no need for refresh

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
