### ISSUE TITLE
Feature: User can view the leaderboard

### ISSUE THREAD

**Issue by jdfenlason** [jdfenlason/FotBets#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the current leaderboard 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be able to press the leaderboard button to see the leaderboard 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-05-24 at 2 34 16 PM](https://user-images.githubusercontent.com/78828085/119392002-21546b00-bc9d-11eb-99e0-2c818ee7f72c.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `data.sql` to to populate users in order to show the leaderboard

### ☁️ Server

- [x] Update `server/index.js` to  create new route to populate leaderboard
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client
- [x] create a state component that collects the leaderboard information
- [x]  create a table that will display the information from the server
- [x] Add a button functionality to the cup that changes screens between screens dynamically 

### 🧑‍⚕️ Clean Up
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
